.github/workflows/main.yml
resolves #4 
Don't merge until we are ready to start generating releases
=> add pipeline to generate releases with semver naming

examples/hybrid_http_proxy/README.md, examples/hybrid_http_proxy/iam.tf, examples/hybrid_http_proxy/main.tf, examples/hybrid_http_proxy/ssm.tf, examples/hybrid_http_proxy/templates/cloud-init.cfg, examples/hybrid_http_proxy/templates/cloud-init.sh, examples/hybrid_http_proxy/terraform.tfvars.example, examples/hybrid_http_proxy/variables.tf, main.tf, templates/cloud-init.sh, variables.tf
the example is setting the no_proxy for local IPs. The example could be extended to create and use a proxy server
resolves #7
=> add option for setting proxy and no_proxy

templates/cloud-init.sh
if proxy config exists, write to /etc/environment and configure for APT
Addresses issue #7
=> check for and configure proxy(s)

.github/workflows/main.yml
There have been 2 failures. Could be due to asterisks in commit message.
#34 raised to properly deal with the issue
=> temporarily remove the semver increment detection for the release.

examples/hybrid/main.tf, examples/hybrid_external_database/main.tf, templates/cloud-init.sh, variables.tf
Set default to shared mutual auth and HTTP
=> add support for PKI mutual auth. Fix SSL listen for HTTPS mode.

examples/hybrid/main.tf, examples/hybrid_external_database/main.tf, templates/cloud-init.sh, variables.tf
=> allow passing server name for Kong SSL config

templates/cloud-init.sh
=> conditionally set the KONG_CLUSTER_CA_CERT on the Data Plane

CHANGELOG.md, CHANGELOG_TEMPLATE.md, CONTRIBUTING.md, Makefile, README.md, modules/database/README.md, modules/database/variables.tf, outputs.tf, variables.tf
Inputs, Outputs, and README details improved
CHANGELOG and CONTRIBUTING added.
resolves #12
=> Module moved from `prototyping` to `maturing`

.github/workflows/pr.yml, CONTRIBUTING.md, README.md
=> check AWS credentials before running, always deactivate at end

examples/hybrid/README.md, examples/hybrid_external_database/README.md, examples/hybrid_http_proxy/README.md
=> fix broken image links in example README files

.github/workflows/pr.yml
=> add KICS to PR workflow

.github/workflows/pr.yml, main.tf, modules/database/rds.tf, modules/database/security_groups.tf, modules/security_groups/main.tf, modules/subnets/main.tf, modules/subnets/variables.tf, outputs.tf, variables.tf
Correct the file paths for ubuntu and amazon-linux in `local.user_data` 
Signed-off-by: Freddie Wright <freddie.wright@engineering.digital.dwp.gov.uk>
=> Correct user data file paths

main.tf, variables.tf
Signed-off-by: Mark Garner <mark.garner1@engineering.digital.dwp.gov.uk>
=> add instance_refresh config to asg

main.tf, modules/database/rds.tf, modules/security_groups/main.tf, modules/security_groups/variables.tf, variables.tf
security group name parameterised
=> security group name parameterised

.github/workflows/pr.yml, docker-image/Dockerfile, docker-image/gateway-entrypoint.sh, docker-image/kong-entrypoint.sh, docker-image/management-plane-entrypoint.sh
=> feat(docker-image): add docker image and job to push to ghcr

main.tf, modules/ecs/main.tf, modules/ecs/variables.tf, templates/ecs/kong_control_plane.tpl, variables.tf
Signed-off-by: Matt Holmes <matthew.holmes@engineering.digital.dwp.gov.uk>
=> Update Task Definition with required environment variables

variables.tf
Signed-off-by: Matt Holmes <matthew.holmes@engineering.digital.dwp.gov.uk>
=> chore(terraform): Correct various typos in variable descriptions

main.tf, modules/ecs/main.tf, modules/ecs/variables.tf, variables.tf
Signed-off-by: Alvaro Lopez Hernandez <alvaro.lopezhernandez@engineering.digital.dwp.gov.uk>
=> fix(variables): add kong_plugins variable at the root module

modules/ec2/main.tf, modules/ec2/outputs.tf, outputs.tf
Signed-off-by: Matt Holmes <matthew.holmes@engineering.digital.dwp.gov.uk>
=> refactor(terraform): Switch to using aws_launch_template resource

modules/ecs/main.tf, templates/ecs/kong_portal.tpl
Signed-off-by: Matt Holmes <matthew.holmes@engineering.digital.dwp.gov.uk>
=> fix(ecs): Add KONG_PLUGINS variable to the Portal Task Definition

modules/ecs/main.tf, templates/ecs/kong_control_plane.tpl, templates/ecs/kong_data_plane.tpl, templates/ecs/kong_portal.tpl
Signed-off-by: Alvaro Lopez Hernandez <alvaro.lopezhernandez@engineering.digital.dwp.gov.uk>
=> chore(terraform): upgrade `template_file` to `templatefile`

main.tf, modules/ec2/main.tf, modules/ec2/variables.tf, modules/ecs/main.tf, modules/ecs/variables.tf, templates/amazon-linux/cloud-init.sh, templates/ecs/kong_control_plane.tpl, templates/ecs/kong_data_plane.tpl, variables.tf
Signed-off-by: Alvaro Lopez Hernandez <alvaro.lopezhernandez@engineering.digital.dwp.gov.uk>
=> feat(*): add statsd-exporter variables

modules/ecs/main.tf, templates/ecs/kong_portal.tpl
This can then be used in custom developer portals
=> feat(portal): add environment to Portal container
